version: "3.0"
services:
  webpack:
    build:
      context: .
      dockerfile: docker/webpack.Dockerfile
    volumes:
      - ./webpack:/app/local/webpack
    ports:
      - "9000:9000"
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    volumes:
      - ./api:/app/local/api
    ports:
      - "5000:5000"
    links:
      - redis
    environment:
      - FLASK_DEBUG=1
  redis:
    image: redis:4.0.2
    ports:
      - "6380:6379"
    command: "redis-server"
